#!/usr/bin/env python

from flask.ext.script import Manager, Server
from flask.ext.assets import ManageAssets

from nox import create_app
from media import CollectLatestMedia

manager = Manager(create_app)
manager.add_command('assets', ManageAssets())
manager.add_command('runserver', Server(host='0.0.0.0'))
manager.add_command('instagram', CollectLatestMedia())


if __name__ == "__main__":
    manager.run()
